site_name: web4app
site_author: kubu lee
site_url: 
repo_url: https://github.com/web4application/web4app.io

dev_addr: web4app.io:5000
theme: yeti

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists

pages:
    - 'Home': 'index.html'
    - 'Getting Started': 'GettingStarted.md'
